import { Requirement } from 'src/domain/entities/requirements.entity';

export function makeRequirementData(
  data: Partial<Requirement> = {},
): Requirement {
  return {
    id_req_visto: data.id_req_visto ?? '1',
    id_projet_fk: data.id_projet_fk ?? '1',
    id_ativ_econ_fk: data.id_ativ_econ_fk ?? '1',
    id_sitc_req_fk: data.id_sitc_req_fk ?? '1',
    id_tipo_edifi_fk: data.id_tipo_edifi_fk ?? '1',
    id_tipo_patrm_fk: data.id_tipo_patrm_fk ?? '1',
    id_risc_ocup_fk: data.id_risc_ocup_fk ?? '1',
    id_sub_tipo_ocup_fk: data.id_sub_tipo_ocup_fk ?? '1',
    id_tipo_ocup_fk: data.id_tipo_ocup_fk ?? '1',
    id_usu_fk: data.id_usu_fk ?? '1',
    ic_pess: data.ic_pess ?? 'A',
    nr_cpf: data.nr_cpf ?? '00000000000',
    nm_pess: data.nm_pess ?? 'Nome Pessoa',
    nr_cnpj: data.nr_cnpj ?? '00000000000000',
    nm_razao_socl: data.nm_razao_socl ?? 'Razão Social',
    ds_titul_estab: data.ds_titul_estab ?? 'Título Estab',
    ic_tipo_ar: data.ic_tipo_ar ?? 'A',
    dt_ini_valid: data.dt_ini_valid ?? new Date(),
    dt_fim_valid: data.dt_fim_valid ?? new Date(),
    nr_telef: data.nr_telef ?? '0000000000',
    nr_celr: data.nr_celr ?? '00000000000',
    ds_email: data.ds_email ?? 'email@exemplo.com',
    nr_area_patrm: data.nr_area_patrm ?? '100',
    nr_area_decld: data.nr_area_decld ?? '100',
    nr_cap_max_pess: data.nr_cap_max_pess ?? '10',
    vl_taxa_pgto: data.vl_taxa_pgto ?? '0',
    nr_pavm: data.nr_pavm ?? '1',
    nr_alt_edf: data.nr_alt_edf ?? '1',
    ic_gnv: data.ic_gnv ?? 'N',
    ic_sist_fixo: data.ic_sist_fixo ?? 'N',
    ic_mat_expl: data.ic_mat_expl ?? 'N',
    id_motiv_isent_tpei_fk: data.id_motiv_isent_tpei_fk ?? '1',
    ds_obs_ar: data.ds_obs_ar ?? '',
    ds_obs: data.ds_obs ?? '',
    ic_stat: data.ic_stat ?? 'A',
    dt_incl: data.dt_incl ?? new Date(),
    dt_atlz: data.dt_atlz ?? new Date(),
    id_protc_fk: data.id_protc_fk ?? '1',
    id_motiv_isent_tax_fk: data.id_motiv_isent_tax_fk ?? '1',
    ic_condm: data.ic_condm ?? 'N',
    ic_esta_condm: data.ic_esta_condm ?? 'N',
    ds_obs_endr: data.ds_obs_endr ?? '',
    id_cidd_x_ome_fk: data.id_cidd_x_ome_fk ?? '1',
    ds_refer_endr: data.ds_refer_endr ?? '',
    ic_reven_gas: data.ic_reven_gas ?? 'N',
    ic_posto_combs: data.ic_posto_combs ?? 'N',
    id_tp_event_temp_fk: data.id_tp_event_temp_fk ?? '1',
    ds_tp_event_temp_outro: data.ds_tp_event_temp_outro ?? '',
    id_ocupc_fk: data.id_ocupc_fk ?? '1',
    dt_emiss_avbc: data.dt_emiss_avbc ?? new Date(),
    ic_sitc_avcb: data.ic_sitc_avcb ?? 'N',
    nr_protc_projt: data.nr_protc_projt ?? '1',
    nr_qtd_botij: data.nr_qtd_botij ?? '0',
    ic_event_abert: data.ic_event_abert ?? 'N',
    nr_latd: data.nr_latd ?? '0',
    nr_long: data.nr_long ?? '0',
    ic_forma: data.ic_forma ?? 'N',
    ic_termo_compr: data.ic_termo_compr ?? 'N',
    ds_obs_termo: data.ds_obs_termo ?? '',
    dt_valid_termo: data.dt_valid_termo ?? new Date(),
    parecer_avcb: data.parecer_avcb ?? '',
    nr_protc_condm: data.nr_protc_condm ?? '1',
    // Adicione outros campos se houver no Requirement
  };
}
