import { Request } from 'src/domain/entities/request.entity';
export function makeRequestData(data: Partial<Request> = {}): Request {
  return {
    id: data.id ?? 1,

    cpf: data.cpf ?? '00000000000',
    personName: data.personName ?? 'Nome Pessoa',
    cnpj: data.cnpj ?? '00000000000000',
    corporateName: data.corporateName ?? 'Razão Social',
    protocolId: data.protocolId ?? 1,

    idProjetFk: data.idProjetFk ?? '1',
    idAtivEconFk: data.idAtivEconFk ?? '1',
    idSitcReqFk: data.idSitcReqFk ?? '1',
    idTipoEdifiFk: data.idTipoEdifiFk ?? '1',
    idTipoPatrmFk: data.idTipoPatrmFk ?? '1',
    idRiscOcupFk: data.idRiscOcupFk ?? '1',
    idSubTipoOcupFk: data.idSubTipoOcupFk ?? '1',
    idTipoOcupFk: data.idTipoOcupFk ?? '1',
    idUsuFk: data.idUsuFk ?? '1',
    icPess: data.icPess ?? 'A',
    dsTitulEstab: data.dsTitulEstab ?? 'Título Estab',
    icTipoAr: data.icTipoAr ?? 'A',
    dtIniValid: data.dtIniValid ?? new Date(),
    dtFimValid: data.dtFimValid ?? new Date(),
    nrTelef: data.nrTelef ?? '0000000000',
    nrCelr: data.nrCelr ?? '00000000000',
    dsEmail: data.dsEmail ?? 'email@exemplo.com',
    nrAreaPatrm: data.nrAreaPatrm ?? '100',
    nrAreaDecld: data.nrAreaDecld ?? '100',
    nrCapMaxPess: data.nrCapMaxPess ?? '10',
    vlTaxaPgto: data.vlTaxaPgto ?? '0',
    nrPavm: data.nrPavm ?? '1',
    nrAltEdf: data.nrAltEdf ?? '1',
    icGnv: data.icGnv ?? 'N',
    icSistFixo: data.icSistFixo ?? 'N',
    icMatExpl: data.icMatExpl ?? 'N',
    idMotivIsentTpeiFk: data.idMotivIsentTpeiFk ?? '1',
    dsObsAr: data.dsObsAr ?? '',
    dsObs: data.dsObs ?? '',
    icStat: data.icStat ?? 'A',
    dtIncl: data.dtIncl ?? new Date(),
    dtAtlz: data.dtAtlz ?? new Date(),
    idMotivIsentTaxFk: data.idMotivIsentTaxFk ?? '1',
    icCondm: data.icCondm ?? 'N',
    icEstaCondm: data.icEstaCondm ?? 'N',
    dsObsEndr: data.dsObsEndr ?? '',
    idCiddXOmeFk: data.idCiddXOmeFk ?? '1',
    dsReferEndr: data.dsReferEndr ?? '',
    icRevenGas: data.icRevenGas ?? 'N',
    icPostoCombs: data.icPostoCombs ?? 'N',
    idTpEventTempFk: data.idTpEventTempFk ?? '1',
    dsTpEventTempOutro: data.dsTpEventTempOutro ?? '',
    idOcupcFk: data.idOcupcFk ?? '1',
    dtEmissAvbc: data.dtEmissAvbc ?? new Date(),
    icSitcAvcb: data.icSitcAvcb ?? 'N',
    nrProtcProjt: data.nrProtcProjt ?? '1',
    nrQtdBotij: data.nrQtdBotij ?? '0',
    icEventAbert: data.icEventAbert ?? 'N',
    nrLatd: data.nrLatd ?? '0',
    nrLong: data.nrLong ?? '0',
    icForma: data.icForma ?? 'N',
    icTermoCompr: data.icTermoCompr ?? 'N',
    dsObsTermo: data.dsObsTermo ?? '',
    dtValidTermo: data.dtValidTermo ?? new Date(),
    parecerAvcb: data.parecerAvcb ?? '',
    nrProtcCondm: data.nrProtcCondm ?? '1',
  };
}
