import { Request } from 'src/domain/entities/request.entity';
import * as dayjs from 'dayjs';
import { TypeormRequestEntity } from '../entities/typeorm-request.entity';
export class RequestMapper {
  static toDomain(entity: TypeormRequestEntity): Request {
    return new Request(
      entity.id,

      entity.cpf,
      entity.personName,
      entity.cnpj,
      entity.corporateName,
      entity.protocolId,
      entity.idProjetFk,

      entity.idAtivEconFk,
      entity.idSitcReqFk,
      entity.idTipoEdifiFk,
      entity.idTipoPatrmFk,
      entity.idRiscOcupFk,
      entity.idSubTipoOcupFk,
      entity.idTipoOcupFk,
      entity.idUsuFk,
      entity.icPess,
      entity.dsTitulEstab,
      entity.icTipoAr,
      entity.dtIniValid ? dayjs(entity.dtIniValid).toDate() : undefined,
      entity.dtFimValid ? dayjs(entity.dtFimValid).toDate() : undefined,
      entity.nrTelef,
      entity.nrCelr,
      entity.dsEmail,
      entity.nrAreaPatrm,
      entity.nrAreaDecld,
      entity.nrCapMaxPess,
      entity.vlTaxaPgto,
      entity.nrPavm,
      entity.nrAltEdf,
      entity.icGnv,
      entity.icSistFixo,
      entity.icMatExpl,
      entity.idMotivIsentTpeiFk,
      entity.dsObsAr,
      entity.dsObs,
      entity.icStat,
      entity.dtIncl ? dayjs(entity.dtIncl).toDate() : undefined,
      entity.dtAtlz ? dayjs(entity.dtAtlz).toDate() : undefined,
      entity.idMotivIsentTaxFk,
      entity.icCondm,
      entity.icEstaCondm,
      entity.dsObsEndr,
      entity.idCiddXOmeFk,
      entity.dsReferEndr,
      entity.icRevenGas,
      entity.icPostoCombs,
      entity.idTpEventTempFk,
      entity.dsTpEventTempOutro,
      entity.idOcupcFk,
      entity.dtEmissAvbc ? dayjs(entity.dtEmissAvbc).toDate() : undefined,
      entity.icSitcAvcb,
      entity.nrProtcProjt,
      entity.nrQtdBotij,
      entity.icEventAbert,
      entity.nrLatd,
      entity.nrLong,
      entity.icForma,
      entity.icTermoCompr,
      entity.dsObsTermo,
      entity.dtValidTermo ? dayjs(entity.dtValidTermo).toDate() : undefined,
      entity.parecerAvcb,
      entity.nrProtcCondm,
    );
  }
}
