import { Requirement } from 'src/domain/entities/requirements.entity';
import * as dayjs from 'dayjs';
import { TypeormRequirementEntity } from '../entities/typeorm-requirement.entity';

export class RequirementMapper {
  static toDomain(entity: TypeormRequirementEntity): Requirement {
    return new Requirement(
      entity.id_req_visto,
      entity.id_projet_fk,
      entity.id_ativ_econ_fk,
      entity.id_sitc_req_fk,
      entity.id_tipo_edifi_fk,
      entity.id_tipo_patrm_fk,
      entity.id_risc_ocup_fk,
      entity.id_sub_tipo_ocup_fk,
      entity.id_tipo_ocup_fk,
      entity.id_usu_fk,
      entity.ic_pess,
      entity.nr_cpf,
      entity.nm_pess,
      entity.nr_cnpj,
      entity.nm_razao_socl,
      entity.ds_titul_estab,
      entity.ic_tipo_ar,
      entity.dt_ini_valid ? dayjs(entity.dt_ini_valid).toDate() : undefined,
      entity.dt_fim_valid ? dayjs(entity.dt_fim_valid).toDate() : undefined,
      entity.nr_telef,
      entity.nr_celr,
      entity.ds_email,
      entity.nr_area_patrm,
      entity.nr_area_decld,
      entity.nr_cap_max_pess,
      entity.vl_taxa_pgto,
      entity.nr_pavm,
      entity.nr_alt_edf,
      entity.ic_gnv,
      entity.ic_sist_fixo,
      entity.ic_mat_expl,
      entity.id_motiv_isent_tpei_fk,
      entity.ds_obs_ar,
      entity.ds_obs,
      entity.ic_stat,
      entity.dt_incl ? dayjs(entity.dt_incl).toDate() : undefined,
      entity.dt_atlz ? dayjs(entity.dt_atlz).toDate() : undefined,
      entity.id_protc_fk,
      entity.id_motiv_isent_tax_fk,
      entity.ic_condm,
      entity.ic_esta_condm,
      entity.ds_obs_endr,
      entity.id_cidd_x_ome_fk,
      entity.ds_refer_endr,
      entity.ic_reven_gas,
      entity.ic_posto_combs,
      entity.id_tp_event_temp_fk,
      entity.ds_tp_event_temp_outro,
      entity.id_ocupc_fk,
      entity.dt_emiss_avbc ? dayjs(entity.dt_emiss_avbc).toDate() : undefined,
      entity.ic_sitc_avcb,
      entity.nr_protc_projt,
      entity.nr_qtd_botij,
      entity.ic_event_abert,
      entity.nr_latd,
      entity.nr_long,
      entity.ic_forma,
      entity.ic_termo_compr,
      entity.ds_obs_termo,
      entity.dt_valid_termo ? dayjs(entity.dt_valid_termo).toDate() : undefined,
      entity.parecer_avcb,
      entity.nr_protc_condm,
    );
  }
}
