import { Request } from 'src/domain/entities/request.entity';
export class RequestPresenter {
  static toHTTP(request: Request) {
    return {
      id: request.id,
      cpf: request.cpf,
      personName: request.personName,
      cnpj: request.cnpj,
      corporateName: request.corporateName,
      protocolId: request.protocolId,

      idProjetFk: request.idProjetFk,
      idAtivEconFk: request.idAtivEconFk,
      idSitcReqFk: request.idSitcReqFk,
      idTipoEdifiFk: request.idTipoEdifiFk,
      idTipoPatrmFk: request.idTipoPatrmFk,
      idRiscOcupFk: request.idRiscOcupFk,
      idSubTipoOcupFk: request.idSubTipoOcupFk,
      idTipoOcupFk: request.idTipoOcupFk,
      idUsuFk: request.idUsuFk,
      icPess: request.icPess,
      dsTitulEstab: request.dsTitulEstab,
      icTipoAr: request.icTipoAr,
      dtIniValid: request.dtIniValid,
      dtFimValid: request.dtFimValid,
      nrTelef: request.nrTelef,
      nrCelr: request.nrCelr,
      dsEmail: request.dsEmail,
      nrAreaPatrm: request.nrAreaPatrm,
      nrAreaDecld: request.nrAreaDecld,
      nrCapMaxPess: request.nrCapMaxPess,
      vlTaxaPgto: request.vlTaxaPgto,
      nrPavm: request.nrPavm,
      nrAltEdf: request.nrAltEdf,
      icGnv: request.icGnv,
      icSistFixo: request.icSistFixo,
      icMatExpl: request.icMatExpl,
      idMotivIsentTpeiFk: request.idMotivIsentTpeiFk,
      dsObsAr: request.dsObsAr,
      dsObs: request.dsObs,
      icStat: request.icStat,
      dtIncl: request.dtIncl,
      dtAtlz: request.dtAtlz,
      idMotivIsentTaxFk: request.idMotivIsentTaxFk,
      icCondm: request.icCondm,
      icEstaCondm: request.icEstaCondm,
      dsObsEndr: request.dsObsEndr,
      idCiddXOmeFk: request.idCiddXOmeFk,
      dsReferEndr: request.dsReferEndr,
      icRevenGas: request.icRevenGas,
      icPostoCombs: request.icPostoCombs,
      idTpEventTempFk: request.idTpEventTempFk,
      dsTpEventTempOutro: request.dsTpEventTempOutro,
      idOcupcFk: request.idOcupcFk,
      dtEmissAvbc: request.dtEmissAvbc,
      icSitcAvcb: request.icSitcAvcb,
      nrProtcProjt: request.nrProtcProjt,
      nrQtdBotij: request.nrQtdBotij,
      icEventAbert: request.icEventAbert,
      nrLatd: request.nrLatd,
      nrLong: request.nrLong,
      icForma: request.icForma,
      icTermoCompr: request.icTermoCompr,
      dsObsTermo: request.dsObsTermo,
      dtValidTermo: request.dtValidTermo,
      parecerAvcb: request.parecerAvcb,
      nrProtcCondm: request.nrProtcCondm,
    };
  }

  static toHTTPList(requests: Request[]) {
    return requests.map((request) => this.toHTTP(request));
  }
}
